- name: installs powerlevel10k on the systems listed in hosts.
  hosts: all 
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install zsh
      become: true
      become_user: root
      ansible.builtin.package:
        name: zsh
        state: present
    - name: Install git
      become: true
      become_user: root
      ansible.builtin.package:
        name: git
        state: present
    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k
        dest: ~/powerlevel10k
    - name: add .zshrc file
      ansible.builtin.copy:
        src: ./powerzshrc
        dest: ~/.zshrc    
    - name: add .p10k file
      ansible.builtin.copy:
        src: ./powerconfig.zsh
        dest: ~/.p10k.zsh
    - name: show correct colors in tmux
      ansible.builtin.copy:
        src: ./colortmux.conf
        dest: ~/.tmux.conf
      
